// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NavToggleButton': string;
  'NavToggleButtonOuter': string;
  'app-navigation-react': string;
}
export const cssExports: CssExports;
export default cssExports;
